== Om denne spesifikasjonen [[Om-spesifikasjonen]]

=== Formål [[Formål]]

Formålet med spesifikasjonen er å legge til rette for en felles måte å beskrive («tagge») innhold på nett. Spesifikasjonen skal bidra til interoperabilitet av innholdsbeskrivelser på tvers av sektorer og CMSer (_Content Management Systems_). Spesifikasjonen muliggjør også maskinell tilgjengeligliggjøring av beskrivelsene. 


=== Omfang og avgrensning [[Omfang-avgrensning]]

Spesifikasjonen er anbefalt brukt til å beskrive innhold som er publisert eller ment å publiseres på nett, samt å utveksle/tilgjengeliggjøre beskrivelsene. Spesifikasjonen er basert på https://data.norge.no/specification/dcat-ap-no/["Standard for beskrivelse av datasett, datatjenester og datakataloger (DCAT-AP-NO) &#x29C9;", window="_blank", role="ext-link"], med utvidelser for å dekke behov identifisert gjennom utarbeidelsen av spesifikasjonen. 

<<del1>> er formulert uavhengig av hvordan de implementeres. 

<<del2>> spesifiserer hvordan kravene beskrevet under <<del1>> skal implementeres i henhold til  https://www.w3.org/RDF/[Resource Description Framework (RDF) &#x29C9;, window="_blank", role="ext-link"]. Beskrivelsene utformet i henhold til spesifikasjonen vil dermed også være RDF-baserte og maskinprosesserbare. 

<<del2>> inneholder også engelske navn (_English name_) og anvendelsesbeskrivelser (_Usage note_). Det gjøres oppmerksom på at engelske navn eller anvendelsesbeskrivelser ikke alle er ordrette sitater fra originale engelske tekster. Vi kan ha valgt en annen tekst til å formidle det samme budskapet på, med mindre vi eksplisitt sier at det er et avvik (dvs. også i meningsinnholdet).

=== Målgrupper [[Målgrupper]]

<<del1>> er ment for deg som skal beskrive («tagge») innhold på nett, uavhengig av teknisk bakgrunn.

<<del2>> er primært for deg som skal utvikle/tilpasse verktøystøtte (f.eks. CMS) for innholdsbeskrivelse. Som støtte til teknisk implementering er det i spesifikasjonen også tatt med en del eksempler i https://www.w3.org/TR/turtle/[RDF Turtle &#x29C9;, window="_blank", role="ext-link"]. Eksemplene i RDF Turtle er kun veiledende, de er ikke komplette og kan også mangle verdier til obligatoriske egenskaper.

Spesifikasjonen er ikke for deg som er leser av det publiserte innholdet som skal beskrives. 

=== Forvaltningsregime [[Forvaltningsregime]]

#_gjelder ikke ennå, siden denne versjonen kun er et forslag i et tidlig hypotese-stadium._#

Spesifikasjonen forvaltes av https://digdir.no[Digitaliseringsdirektoratet (Digdir) &#x29C9;, window="_blank", role="ext-link"].

Utarbeidelse av nye versjoner av spesifikasjonen initieres av Digdir. Mindre endringer håndteres av Digdir. Ved behov for større endringer vil Digdir sette sammen arbeidsgruppe med representanter fra relevante virksomheter, for utarbeidelse av forslag til den reviderte versjonen som sendes ut til bred kommentering før fastsetting.

=== Om kravnivåene i spesifikasjonen [[Om-kravnivåene]]

Spesifikasjonen bruker ordene «obligatorisk/skal» (_"mandatory/shall"_), «anbefalt/bør» (_"recommended/should"_) og «valgfri/kan» (_"optional/may"_) som har følgende betydning:

* *Obligatorisk/skal*: Du skal oppgi informasjonen.
* *Anbefalt/bør*: Du bør oppgi informasjonen hvis den er tilgjengelig.
* *Valgfri/kan*: Du kan oppgi informasjonen, men ikke påkrevd.